// <auto-generated />
using System;
using Airport.Service.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airport.Service.Migrations
{
    [DbContext(typeof(AirportContext))]
    [Migration("20250720190943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Airport.Service.Repository.Entities.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AirportCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Airport", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Concourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TerminalId");

                    b.ToTable("Concourse", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Gate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConcourseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GateType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConcourseId");

                    b.ToTable("Gate", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Runway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirportId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsParallel")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MagneticHeading")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Runway", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Taxiway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AirportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Taxiway", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AirportId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("Terminal", (string)null);
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Concourse", b =>
                {
                    b.HasOne("Airport.Service.Repository.Entities.Terminal", "Terminal")
                        .WithMany("Concourses")
                        .HasForeignKey("TerminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Terminal");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Gate", b =>
                {
                    b.HasOne("Airport.Service.Repository.Entities.Concourse", "Concourse")
                        .WithMany("Gates")
                        .HasForeignKey("ConcourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concourse");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Runway", b =>
                {
                    b.HasOne("Airport.Service.Repository.Entities.Airport", null)
                        .WithMany("Runways")
                        .HasForeignKey("AirportId");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Taxiway", b =>
                {
                    b.HasOne("Airport.Service.Repository.Entities.Airport", null)
                        .WithMany("Taxiways")
                        .HasForeignKey("AirportId");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Terminal", b =>
                {
                    b.HasOne("Airport.Service.Repository.Entities.Airport", "Airport")
                        .WithMany("Terminals")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Airport", b =>
                {
                    b.Navigation("Runways");

                    b.Navigation("Taxiways");

                    b.Navigation("Terminals");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Concourse", b =>
                {
                    b.Navigation("Gates");
                });

            modelBuilder.Entity("Airport.Service.Repository.Entities.Terminal", b =>
                {
                    b.Navigation("Concourses");
                });
#pragma warning restore 612, 618
        }
    }
}
