// <auto-generated />
using System;
using FlightSchedule.Api.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightSchedule.Api.Migrations
{
    [DbContext(typeof(FlightsDbContext))]
    partial class FlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("FlightSchedule.Api.Models.ArrivingFlight", b =>
                {
                    b.Property<string>("Flight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aircraft")
                        .HasColumnType("TEXT");

                    b.Property<string>("Airline")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Flight");

                    b.ToTable("Arrivals");
                });

            modelBuilder.Entity("FlightSchedule.Api.Models.DepartingFlight", b =>
                {
                    b.Property<string>("Flight")
                        .HasColumnType("TEXT");

                    b.Property<string>("Aircraft")
                        .HasColumnType("TEXT");

                    b.Property<string>("Airline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Flight");

                    b.ToTable("Departures");
                });
#pragma warning restore 612, 618
        }
    }
}
